version: '3.4'

services:
  sensei_user_service:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: src/Services/User/User.Api/Dockerfile

  SenseiMongodb:
    container_name: SenseiMongodb
    image: mongo
  mongo-express:
    image: mongo-express
  portainer:
    image: portainer/portainer-ce

  sensei_auth_service:
    image: ${DOCKER_REGISTRY-}auth
    build:
      context: .
      dockerfile: src/Services/Auth/Dockerfile

volumes:
  SeseiMongoDb_data:
  portainer_data:

